#!/usr/bin/env bash
# shellcheck shell=bash
#
# scripts/tidy

set -euo pipefail

ROOT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." && pwd)"

source "$ROOT_DIR/scripts/lib/lib.sh"
source "$ROOT_DIR/scripts/lib/paths.sh"

tidy() {
  info "Running tidy..."
  go mod tidy -v
  ok "... complete."
}

fmt() {
  info "Running gofmt..."
  gofmt -w .
  ok "... complete."
}

main() {
  need_cmd go
  need_cmd gofmt

  info "Cleaning up project..."
  tidy
  fmt
  ok "... cleanup complete."
}

main "$@"
